export enum AuthError {
  USER_NOT_FOUND = 'AUTH_USER_NOT_FOUND',
  INVALID_PASSWORD = 'AUTH_INVALID_PASSWORD',
  EMAIL_NOT_VERIFIED = 'AUTH_EMAIL_NOT_VERIFIED',
  PIN_REQUIRED = 'AUTH_PIN_REQUIRED',
  INVALID_TOTP = 'AUTH_INVALID_TOTP',
  SESSION_REMOVE_CURRENT = 'AUTH_SESSION_REMOVE_CURRENT',
  EMAIL_EXISTS = 'AUTH_EMAIL_EXISTS',
  TOKEN_NOT_FOUND = 'AUTH_TOKEN_NOT_FOUND',
  TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  FORBIDDEN = 'AUTH_FORBIDDEN',
  ADMIN_CANNOT_BE_DEACTIVATED = 'AUTH_ADMIN_CANNOT_BE_DEACTIVATED',
  ADMIN_CANNOT_BE_DELETED = 'AUTH_ADMIN_CANNOT_BE_DELETED',
}

export enum SubscriptionError {
  PLAN_NOT_FOUND = 'SUBSCRIPTION_PLAN_NOT_FOUND',
  PLAN_ALREADY_EXISTS = 'SUBSCRIPTION_PLAN_ALREADY_EXISTS',
  CANNOT_DELETE_ASSIGNED_PLAN = 'SUBSCRIPTION_CANNOT_DELETE_ASSIGNED_PLAN',
  LIMIT_REACHED = 'SUBSCRIPTION_LIMIT_REACHED',
  PRICE_NOT_FOUND = 'SUBSCRIPTION_PRICE_NOT_FOUND',
  PRICE_DOES_NOT_BELONG_TO_PLAN = 'SUBSCRIPTION_PRICE_DOES_NOT_BELONG_TO_PLAN',
}

export enum GeneralError {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum AccountError {
  NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  ALREADY_EXISTS = 'ACCOUNT_ALREADY_EXISTS',
  CREATION_FAILED = 'ACCOUNT_CREATION_FAILED',
  UPDATE_FAILED = 'ACCOUNT_UPDATE_FAILED',
  DELETION_FAILED = 'ACCOUNT_DELETION_FAILED',
}

export enum CategoryError {
  NOT_FOUND = 'CATEGORY_NOT_FOUND',
  ALREADY_EXISTS = 'CATEGORY_ALREADY_EXISTS',
  SELF_PARENT = 'CATEGORY_SELF_PARENT',
  CREATION_FAILED = 'CATEGORY_CREATION_FAILED',
  UPDATE_FAILED = 'CATEGORY_UPDATE_FAILED',
  DELETION_FAILED = 'CATEGORY_DELETION_FAILED',
}

export enum TagError {
  NOT_FOUND = 'TAG_NOT_FOUND',
  ALREADY_EXISTS = 'TAG_ALREADY_EXISTS',
  CREATION_FAILED = 'TAG_CREATION_FAILED',
  UPDATE_FAILED = 'TAG_UPDATE_FAILED',
  DELETION_FAILED = 'TAG_DELETION_FAILED',
}

export enum OperationError {
  NOT_FOUND = 'OPERATION_NOT_FOUND',
  CREATION_FAILED = 'OPERATION_CREATION_FAILED',
  UPDATE_FAILED = 'OPERATION_UPDATE_FAILED',
  DELETION_FAILED = 'OPERATION_DELETION_FAILED',
}

export enum RecurrenceError {
  NOT_FOUND = 'RECURRENCE_NOT_FOUND',
  PLAN_NOT_SUPPORTED = 'RECURRENCE_PLAN_NOT_SUPPORTED',
  CREATION_FAILED = 'RECURRENCE_CREATION_FAILED',
  UPDATE_FAILED = 'RECURRENCE_UPDATE_FAILED',
  DELETION_FAILED = 'RECURRENCE_DELETION_FAILED',
}

export enum NotificationError {
  NOT_FOUND = 'NOTIFICATION_NOT_FOUND',
  CREATION_FAILED = 'NOTIFICATION_CREATION_FAILED',
  DELETION_FAILED = 'NOTIFICATION_DELETION_FAILED',
  MARK_READ_FAILED = 'NOTIFICATION_MARK_READ_FAILED',
}

export enum FileError {
  NOT_FOUND = 'FILE_NOT_FOUND',
  INVALID_FORMAT = 'FILE_INVALID_FORMAT',
  SIZE_TOO_LARGE = 'FILE_SIZE_TOO_LARGE',
  NO_ROWS = 'FILE_NO_ROWS',
  EMPTY = 'FILE_EMPTY',
}
