export enum AuthError {
  USER_NOT_FOUND = "AUTH_USER_NOT_FOUND",
  INVALID_PASSWORD = "AUTH_INVALID_PASSWORD",
  EMAIL_NOT_VERIFIED = "AUTH_EMAIL_NOT_VERIFIED",
  PIN_REQUIRED = "AUTH_PIN_REQUIRED",
  INVALID_TOTP = "AUTH_INVALID_TOTP",
  SESSION_REMOVE_CURRENT = "AUTH_SESSION_REMOVE_CURRENT",
  EMAIL_EXISTS = "AUTH_EMAIL_EXISTS",
  TOKEN_NOT_FOUND = "AUTH_TOKEN_NOT_FOUND",
  TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED",
  UNAUTHORIZED = "AUTH_UNAUTHORIZED",
  FORBIDDEN = "AUTH_FORBIDDEN",
  ADMIN_CANNOT_BE_DEACTIVATED = "AUTH_ADMIN_CANNOT_BE_DEACTIVATED",
  ADMIN_CANNOT_BE_DELETED = "AUTH_ADMIN_CANNOT_BE_DELETED",
  BAD_CREDENTIALS = "AUTH_BAD_CREDENTIALS",
}

export enum SubscriptionError {
  PLAN_NOT_FOUND = "SUBSCRIPTION_PLAN_NOT_FOUND",
  PLAN_ALREADY_EXISTS = "SUBSCRIPTION_PLAN_ALREADY_EXISTS",
  CANNOT_DELETE_ASSIGNED_PLAN = "SUBSCRIPTION_CANNOT_DELETE_ASSIGNED_PLAN",
  LIMIT_REACHED = "SUBSCRIPTION_LIMIT_REACHED",
  MONTHLY_LIMIT_REACHED = "SUBSCRIPTION_MONTHLY_LIMIT_REACHED",
  PRICE_NOT_FOUND = "SUBSCRIPTION_PRICE_NOT_FOUND",
  PRICE_DOES_NOT_BELONG_TO_PLAN = "SUBSCRIPTION_PRICE_DOES_NOT_BELONG_TO_PLAN",
}

export enum GeneralError {
  USER_NOT_FOUND = "USER_NOT_FOUND",
  NOT_FOUND = "NOT_FOUND",
  BAD_REQUEST = "BAD_REQUEST",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
}

export enum AccountError {
  NOT_FOUND = "ACCOUNT_NOT_FOUND",
  ALREADY_EXISTS = "ACCOUNT_ALREADY_EXISTS",
  CREATION_FAILED = "ACCOUNT_CREATION_FAILED",
  UPDATE_FAILED = "ACCOUNT_UPDATE_FAILED",
  DELETION_FAILED = "ACCOUNT_DELETION_FAILED",
  CANNOT_DELETE_LAST = "ACCOUNT_CANNOT_DELETE_LAST",
}

export enum CategoryError {
  NOT_FOUND = "CATEGORY_NOT_FOUND",
  ALREADY_EXISTS = "CATEGORY_ALREADY_EXISTS",
  SELF_PARENT = "CATEGORY_SELF_PARENT",
  CREATION_FAILED = "CATEGORY_CREATION_FAILED",
  UPDATE_FAILED = "CATEGORY_UPDATE_FAILED",
  DELETION_FAILED = "CATEGORY_DELETION_FAILED",
}

export enum TagError {
  NOT_FOUND = "TAG_NOT_FOUND",
  ALREADY_EXISTS = "TAG_ALREADY_EXISTS",
  CREATION_FAILED = "TAG_CREATION_FAILED",
  UPDATE_FAILED = "TAG_UPDATE_FAILED",
  DELETION_FAILED = "TAG_DELETION_FAILED",
}

export enum OperationError {
  NOT_FOUND = "OPERATION_NOT_FOUND",
  CREATION_FAILED = "OPERATION_CREATION_FAILED",
  UPDATE_FAILED = "OPERATION_UPDATE_FAILED",
  DELETION_FAILED = "OPERATION_DELETION_FAILED",
  TRANSFER_SAME_ACCOUNT = "OPERATION_TRANSFER_SAME_ACCOUNT",
  TRANSFER_TARGET_REQUIRED = "OPERATION_TRANSFER_TARGET_REQUIRED",
  TRANSFER_ACCOUNT_MUST_DIFFER = "OPERATION_TRANSFER_ACCOUNT_MUST_DIFFER",
}

export enum RecurrenceError {
  NOT_FOUND = "RECURRENCE_NOT_FOUND",
  PLAN_NOT_SUPPORTED = "RECURRENCE_PLAN_NOT_SUPPORTED",
  CREATION_FAILED = "RECURRENCE_CREATION_FAILED",
  UPDATE_FAILED = "RECURRENCE_UPDATE_FAILED",
  DELETION_FAILED = "RECURRENCE_DELETION_FAILED",
  UPDATE_NOT_ALLOWED = "RECURRENCE_UPDATE_NOT_ALLOWED",
}

export enum NotificationError {
  NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  CREATION_FAILED = "NOTIFICATION_CREATION_FAILED",
  DELETION_FAILED = "NOTIFICATION_DELETION_FAILED",
  MARK_READ_FAILED = "NOTIFICATION_MARK_READ_FAILED",
  MARK_ALL_READ_FAILED = "NOTIFICATION_MARK_ALL_READ_FAILED",
  USER_ID_REQUIRED = "NOTIFICATION_USER_ID_REQUIRED",
  FIND_FAILED = "NOTIFICATION_FIND_FAILED",
  AT_LEAST_ONE_LANGUAGE_REQUIRED = "NOTIFICATION_AT_LEAST_ONE_LANGUAGE_REQUIRED",
}

export enum AiUploadError {
  INSUFFICIENT_TOKENS = "AI_UPLOAD_INSUFFICIENT_TOKENS",
  NO_CATEGORIES = "AI_UPLOAD_NO_CATEGORIES",
  NO_OPERATIONS = "AI_UPLOAD_NO_OPERATIONS",
  PARSE_ERROR = "AI_UPLOAD_PARSE_ERROR",
  PROCESS_FAILED = "AI_UPLOAD_PROCESS_FAILED",
  TOKEN_COUNT_FAILED = "AI_UPLOAD_TOKEN_COUNT_FAILED",
  INVALID_DOCUMENT = "AI_UPLOAD_INVALID_DOCUMENT",
  UNREADABLE = "AI_UPLOAD_UNREADABLE",
  NO_DATA = "AI_UPLOAD_NO_DATA",
}

export enum FileError {
  NOT_FOUND = "FILE_NOT_FOUND",
  INVALID_FORMAT = "FILE_INVALID_FORMAT",
  INVALID_FORMAT_SPREADSHEET = "FILE_INVALID_FORMAT_SPREADSHEET",
  SIZE_TOO_LARGE = "FILE_SIZE_TOO_LARGE",
  NO_ROWS = "FILE_NO_ROWS",
  EMPTY = "FILE_EMPTY",
  SHEET_MISSING = "FILE_SHEET_MISSING",
  SHEET_EMPTY = "FILE_SHEET_EMPTY",
  ROW_EMPTY_REQUIRED_FIELDS = "FILE_ROW_EMPTY_REQUIRED_FIELDS",
  ROW_INVALID_TYPE = "FILE_ROW_INVALID_TYPE",
  ROW_EMPTY_CATEGORY = "FILE_ROW_EMPTY_CATEGORY",
  COLUMN_MISSING = "FILE_COLUMN_MISSING",
  DATE_PARSE_ERROR = "FILE_DATE_PARSE_ERROR",
  DATE_EMPTY = "FILE_DATE_EMPTY",
  PARSE_ERROR = "FILE_PARSE_ERROR",
}

export const ALL_ERROR_CODES = [
  ...Object.values(AuthError),
  ...Object.values(SubscriptionError),
  ...Object.values(GeneralError),
  ...Object.values(AccountError),
  ...Object.values(CategoryError),
  ...Object.values(TagError),
  ...Object.values(OperationError),
  ...Object.values(RecurrenceError),
  ...Object.values(NotificationError),
  ...Object.values(AiUploadError),
  ...Object.values(FileError),
] as const;
